[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xe6efff"
yellow = "0xd19a66"

[colors.cursor]
cursor = "#abb2bf"
text = "0x000000"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.primary]
background = "0x282c34"
bright_foreground = "0xe6efff"
foreground = "0xabb2bf"
